server:
  port: 8081

spring:
  application:
    name: USER-SERVICE
  config:
    import: optional:configserver:http://localhost:8085
  #  profiles:    (this is create only for testing prupose line profiles:active )
  #    active: prod
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-28295594.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oa98byqz65KTkuX05d7
            client-secret: SaQaaMB2FV5JWqxZTyP3GJOr4ZDfHnT0bavtZxfL

        provider:
          okta:
            issuer-uri: https://dev-28295594.okta.com/oauth2/default


  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Pass@123word$
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#        defaultZone: http://localhost:8761/eureka


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s

  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 2s


okta:
  oauth2:
    issuer: https://dev-28295594.okta.com/oauth2/default
    audience: api://default
